Pandas
Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

In [5]:
#dataframe
import pandas as pd

df=pd.DataFrame({'population':[35,63,80,20],'GDP':[312,600,350,425],'surface area':[18373,18373,18363,19374],'HDI':[10,12,19,15],
                 'continent':['abe','dez','ghi','jkl']},columns=['population','GDP','surface area','continent'])   #columns needed otherwise it will create index
df

   population  GDP  surface area continent
0          35  312         18373       abe
1          63  600         18373       dez
2          80  350         18363       ghi
3          20  425         19374       jkl

In [ ]:
#setting custom index
df.index=['canada','france','germany','italy']

In [ ]:
#for 2d arrays       #we will only use tabular data so just remember this way of fetching 2d array or table. no need learning 3d or aboves
#in numpy array we used 
#fetch 1st 3rd 4th 6th rows
#a[[0,2,3,5]]

#and used foloowing to fetch columns
#a[:,[0,2,3]]  #the second part is columns whilw the 1st part means : all rows

#used following for boolean indexing
#a[(a>50)&(a%2==0)]

#fetch 2nd and 3rd row and 2nd and 3rd column
#a2[1:,1:3]

In [ ]:
###indexing 
#only rows retrieve   loc   iloc

print(df.loc['canada'])

print()

print(df.iloc[-1])

print()

print(df.iloc[[0,1,-1]])  #multiple rows/records retrieve

print()

population         35
GDP               312
surface area    18373
continent         abe
Name: canada, dtype: object

population         20
GDP               425
surface area    19374
continent         jkl
Name: italy, dtype: object

        population  GDP  surface area continent
canada          35  312         18373       abe
france          63  600         18373       dez
italy           20  425         19374       jkl

In [ ]:
#column retrieve   -- no need to use loc iloc bcz thats index/related to records
print(df[['population','GDP']])   #only columns retrieve

print()

print(df.loc['france':'italy','population'])  #rows plus one column ret.

print()

print(df.loc['france':'italy',['population','GDP']])  #rows plus columns retrieve

         population  GDP
canada           35  312
france           63  600
germany          80  350
italy            20  425

france     63
germany    80
italy      20
Name: population, dtype: int64

         population  GDP
france           63  600
germany          80  350
italy            20  425

In [ ]:
##### iloc
print(df.iloc[1:3],[0,3])   #1st one rows   2nd one columns. rows plus columns ret.

print()

print(df.iloc[1:3,1:3])   #rows and columns ret. by slicing

         population  GDP  surface area continent
france           63  600         18373       dez
germany          80  350         18363       ghi [0, 3]

         GDP  surface area
france   600         18373
germany  350         18363

In [2]:
import numpy as np
import pandas as pd

In [34]:
#using lists
students_data=[[100,80,10],[90,70,7],[120,100,14],[80,50,2]]

students_data=pd.DataFrame(students_data,columns=['iq','marks','package'])
students_data

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [60]:
#using dicts.
students_dict={'name':['ali','iqra','waleed','adnan','umar','ayan'],
               'id':[100,90,120,80,0,0],'marks':[80,70,100,50,0,0],
               'package':[10,7,14,2,0,0]}

students=pd.DataFrame(students_dict)
students.set_index('name',inplace=True)
students

         id  marks  package
name
ali     100     80       10
iqra     90     70        7
waleed  120    100       14
adnan    80     50        2
umar      0      0        0
ayan      0      0        0

In [3]:
#using read_csv
movies=pd.read_csv('data/movies.csv')   #bcz the data is in current working directory so simply give data then file name for path
#movies

In [4]:
ipl_data=pd.read_csv('data/ipl-matches.csv')

In [12]:
#######DataFrame attributes and methods
#shape
print(movies.shape)
print(ipl_data.shape)

print()

#dtypes
print(movies.dtypes)
print()
print(ipl_data.dtypes)

(1629, 18)
(950, 20)

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [15]:
#index
print(movies.index)
print(ipl_data.index)

print()

#columns
print(movies.columns)
print(ipl_data.columns)
print(students.columns)

RangeIndex(start=0, stop=1629, step=1)
RangeIndex(start=0, stop=950, step=1)

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')
Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')
Index(['id', 'marks', 'package'], dtype='object')

In [17]:
#values
print(students.values)
print(ipl_data.values)

[[100  80  10]
 [ 90  70   7]
 [120 100  14]
 [ 80  50   2]
 [  0   0   0]
 [  0   0   0]]
[[1312200 'Ahmedabad' '2022-05-29' ...
  "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']"
  'CB Gaffaney' 'Nitin Menon']
 [1312199 'Ahmedabad' '2022-05-27' ...
  "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']"
  'CB Gaffaney' 'Nitin Menon']
 [1312198 'Kolkata' '2022-05-25' ...
  "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']"
  'J Madanagopal' 'MA Gough']
 ...
 [335984 'Delhi' '2008-04-19' ...
  "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']"
  'Aleem Dar' 'GA Pratapkumar']
 [335983 'Chandigarh' '2008-04-19' ...
  "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']"
  'MR Benson' 'SL Shastri']
 [335982 'Bangalore' '2008-04-18' ...
  "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']"
  'Asad Rauf' 'RE Koertzen']]

In [22]:
#head and tail
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [23]:
ipl_data.tail(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [24]:
#sample
ipl_data.sample(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
266,1136608,Indore,2018-05-14,2018,48,Kings XI Punjab,Royal Challengers Bangalore,Holkar Cricket Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,10.0,NaN,UT Yadav,"['KL Rahul', 'CH Gayle', 'KK Nair', 'AJ Finch'...","['V Kohli', 'PA Patel', 'MM Ali', 'AB de Villi...",BNJ Oxenford,VK Sharma
255,1136619,Kolkata,2018-05-25,2018,Qualifier,Sunrisers Hyderabad,Kolkata Knight Riders,Eden Gardens,Kolkata Knight Riders,field,N,Sunrisers Hyderabad,Runs,14.0,NaN,Rashid Khan,"['WP Saha', 'S Dhawan', 'KS Williamson', 'Shak...","['CA Lynn', 'SP Narine', 'N Rana', 'RV Uthappa...",HDPK Dharmasena,Nitin Menon
776,419164,Mumbai,2010-04-24,2009/10,3rd Place Play-Off,Royal Challengers Bangalore,Deccan Chargers,Dr DY Patil Sports Academy,Deccan Chargers,bat,N,Royal Challengers Bangalore,Wickets,9.0,NaN,A Kumble,"['JH Kallis', 'R Dravid', 'KP Pietersen', 'RV ...","['AC Gilchrist', 'MD Mishra', 'Anirudh Singh',...",RE Koertzen,SJA Taufel
240,1175369,Jaipur,2019-04-02,2019,14,Royal Challengers Bangalore,Rajasthan Royals,Sawai Mansingh Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,S Gopal,"['V Kohli', 'PA Patel', 'AB de Villiers', 'SO ...","['AM Rahane', 'JC Buttler', 'SPD Smith', 'RA T...",AY Dandekar,M Erasmus
642,548367,Bangalore,2012-05-14,2012,62,Royal Challengers Bangalore,Mumbai Indians,M Chinnaswamy Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,AT Rayudu,"['CH Gayle', 'TM Dilshan', 'V Kohli', 'SS Tiwa...","['HH Gibbs', 'SR Tendulkar', 'RG Sharma', 'KD ...",S Das,BR Doctrove

In [26]:
#info
print(movies.info())

#ipl_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB
None

In [27]:
#describe
movies.describe()

#ipl_data.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [28]:
#isnull
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [31]:
#duplicated
movies.duplicated().sum()

#students.duplicated().sum()

np.int64(0)

In [36]:
#rename
print(students_data)

print()

students_data.rename(columns={'marks':'percent','package':'lpa'},inplace=True)
print(students_data)

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

    iq  percent  lpa
0  100       80   10
1   90       70    7
2  120      100   14
3   80       50    2

In [40]:
#####   math methods
#sum
print(students_data.sum(axis=0))

print()

print(students_data.mean(axis=1))

print()

print(students_data.var())

iq         390
percent    300
lpa         33
dtype: int64

0    63.333333
1    55.666667
2    78.000000
3    44.000000
dtype: float64

iq         291.666667
percent    433.333333
lpa         25.583333
dtype: float64

In [ ]:
#### fetching data  fetching columns or fetching rows/index

In [43]:
#selecting single columns
print(movies.columns)

print()

movies['title_x']

#ipl_data['Venue']

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: object

In [47]:
#select multiple columns     use list within the square brackets
movies[['year_of_release','actors','title_x']]

,year_of_release,actors,title_x
0,2019,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,Uri: The Surgical Strike
1,2019,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,Battalion 609
2,2019,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,The Accidental Prime Minister (film)
3,2019,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,Why Cheat India
4,2018,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,Evening Shadows
...,...,...,...
1624,2001,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,Tera Mera Saath Rahen
1625,2001,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,Yeh Zindagi Ka Safar
1626,2018,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,Sabse Bada Sukh
1627,2019,Gippy Grewal|Zareen Khan|,Daaka
1628,2011,Fawad Khan|,Humsafar

In [48]:
####selecting rows from a DataFrame
#bcz rows are fetched with index and we use iloc and loc also

#single row
movies.iloc[5]

title_x                                                   Soni (film)
imdb_id                                                     tt6078866
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link                   https://en.wikipedia.org/wiki/Soni_(film)
title_y                                                          Soni
original_title                                                   Soni
is_adult                                                            0
year_of_release                                                  2018
runtime                                                            97
genres                                                          Drama
imdb_rating                                                       7.2
imdb_votes                                                       1595
story               Soni  a young policewoman in Delhi  and her su...
summary             While fighting crimes against women in Delhi  ...
tagline                                                           NaN
actors              Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...
wins_nominations                               3 wins & 5 nominations
release_date                                    18 January 2019 (USA)
Name: 5, dtype: object

In [49]:
#multiple rows select
movies.iloc[:5]    #first five rows

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [50]:
#fancy indexing ---used when no pathern there 
#select 1st 3rd and 4th rows
movies.iloc[[0,4,5]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)

In [61]:
#loc
print(students)

print()

students.loc['ali']

         id  marks  package
name
ali     100     80       10
iqra     90     70        7
waleed  120    100       14
adnan    80     50        2
umar      0      0        0
ayan      0      0        0

id         100
marks       80
package     10
Name: ali, dtype: int64

In [62]:
students.loc[['ali','iqra','waleed']]

         id  marks  package
name
ali     100     80       10
iqra     90     70        7
waleed  120    100       14

In [63]:
students.iloc[[0,3,4]]

        id  marks  package
name
ali    100     80       10
adnan   80     50        2
umar     0      0        0

In [64]:
############selecting both rows and columns
movies.iloc[0:3,0:3]   #first part row and 2nd part column

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [65]:
movies.loc[0:2,'title_x':'poster_path']

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [ ]:
https://colab.research.google.com/drive/1k_CV931NE4_jMxmu3k2ASPMmIA4g5Wcn?usp=sharing#scrollTo=LGrzybQ6ad_d

In [ ]:
#end

Series
A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

In [5]:
#import pandas
#!pip install pandas

import pandas as pd
#import numpy as np

In [ ]:
#series ---- like python list or numpy array

population =pd.Series([35,63,80,60])    #S capital. Series
population

0    35
1    63
2    80
3    60
dtype: int64

In [8]:
#name this series
population.name='G7 population in millions'
population

0    35
1    63
2    80
3    60
Name: G7 population in millions, dtype: int64

In [9]:
population.dtype

dtype('int64')

In [10]:
type(population)

pandas.core.series.Series

In [13]:
#population.values #it will convert it into numpyarray
print(type(population.values))

population.index

<class 'numpy.ndarray'>

RangeIndex(start=0, stop=4, step=1)

In [ ]:
population.index=['canada','france','germany','italy',]   #use , at the end

In [18]:
#initiating + renaming + indexing     in one step
population=pd.Series({'canada':35,'france':63,'italy':26,'japan':22},name='G7 population')
population

canada    35
france    63
italy     26
japan     22
Name: G7 population, dtype: int64

In [21]:
#another way using list
population=pd.Series([35,63,27,48],index=['canada','france','italy','japan'],name='G7 population')
population

canada    35
france    63
italy     27
japan     48
Name: G7 population, dtype: int64

In [22]:
#calling by index
pd.Series(population,index=['france','japan'])

france    63
japan     48
Name: G7 population, dtype: int64

In [ ]:
print(population[0])   #at 0 index is canada so population 35

print(population['canada'])  #35 population

35
35

C:\Users\ASUS\AppData\Local\Temp\ipykernel_7944\776713825.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(population[0])

In [28]:
#to select multiple items use list    [[]]
population[['italy','france']]

italy     27
france    63
Name: G7 population, dtype: int64

In [ ]:
# slicing
population[0:3]

canada    35
france    63
italy     27
Name: G7 population, dtype: int64

In [31]:
#slicing
population['canada':'italy']

canada    35
france    63
italy     27
Name: G7 population, dtype: int64

In [ ]:
############## iloc     and       loc
print(population.iloc[0])      #iloc used when you fetching data with the original indexing 0 1 2 ...

population.loc['canada']       #used when to fetch data with custom indexing

35

np.int64(35)

In [36]:
population.iloc[0:4]

canada    35
france    63
italy     27
japan     48
Name: G7 population, dtype: int64

In [ ]:
population.iloc[-1]   #to fetch lst item

np.int64(48)

In [38]:
population.iloc[-2:-4:-1]

italy     27
france    63
Name: G7 population, dtype: int64

In [44]:
#conditional
print(population>10)

print("")

print(population.std())

population.mean

canada    True
france    True
italy     True
japan     True
Name: G7 population, dtype: bool

15.75595125658873

<bound method Series.mean of canada    35
france    63
italy     27
japan     48
Name: G7 population, dtype: int64>

In [ ]:
import numpy as np
np.log(population)

population['italy','france'].mean()


#modify
population['canada']=48
population.iloc[-1]=500


population.mean
population*100

#####################end